<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Van Anh Nguyenova">

<title>Titanic Survival Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DWV_Assignment 1_VAN_files/libs/clipboard/clipboard.min.js"></script>
<script src="DWV_Assignment 1_VAN_files/libs/quarto-html/quarto.js"></script>
<script src="DWV_Assignment 1_VAN_files/libs/quarto-html/popper.min.js"></script>
<script src="DWV_Assignment 1_VAN_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DWV_Assignment 1_VAN_files/libs/quarto-html/anchor.min.js"></script>
<link href="DWV_Assignment 1_VAN_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DWV_Assignment 1_VAN_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DWV_Assignment 1_VAN_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DWV_Assignment 1_VAN_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DWV_Assignment 1_VAN_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Titanic Survival Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Van Anh Nguyenova </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<div style="text-align: justify;">
<p>This project explores survival outcomes on the Titanic using the <code>titanic_train</code> dataset from the titanic R package. The Titanic was a British ship that sank in the North Atlantic Ocean on 15 April 1912 after hitting an iceberg during its first voyage, which was one of the most infamous maritime disasters in history.</p>
<p>The dataset includes information about 891 passengers, such as their age, gender, ticket class, fare paid, and whether they survived. By conducting exploratory data analysis (EDA), the project uncovers meaningful patterns in passenger demographics and visualizes survival distributions across key variables. This includes the impact of traveling alone versus with family, the effect of ticket fare as a proxy for class, and differences in survival across age groups and genders. Visual tools such as bar charts, density plots, ridge plots, box plots, and scatter plots are used to support the analysis and insights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(titanic)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exploratory-analysis" class="level1">
<h1>Exploratory Analysis</h1>
<section id="data-overview" class="level2">
<h2 class="anchored" data-anchor-id="data-overview">Data Overview</h2>
<p>First, we aim to analyse the composition of the Titanic’s passengers and their survival rates. There is a well-known notion of “women and children first,” suggesting that gender may have played a significant role in survival outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"titanic_train"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(titanic_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 891
Columns: 12
$ PassengerId &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ Survived    &lt;int&gt; 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1…
$ Pclass      &lt;int&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3…
$ Name        &lt;chr&gt; "Braund, Mr. Owen Harris", "Cumings, Mrs. John Bradley (Fl…
$ Sex         &lt;chr&gt; "male", "female", "female", "female", "male", "male", "mal…
$ Age         &lt;dbl&gt; 22, 38, 26, 35, 35, NA, 54, 2, 27, 14, 4, 58, 20, 39, 14, …
$ SibSp       &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0…
$ Parch       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0…
$ Ticket      &lt;chr&gt; "A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", "37…
$ Fare        &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625,…
$ Cabin       &lt;chr&gt; "", "C85", "", "C123", "", "", "E46", "", "", "", "G6", "C…
$ Embarked    &lt;chr&gt; "S", "C", "S", "S", "S", "Q", "S", "S", "S", "C", "S", "S"…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Female percentage</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>total_passengers <span class="ot">&lt;-</span> <span class="fu">nrow</span>(titanic_train)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>total_females <span class="ot">&lt;-</span> <span class="fu">sum</span>(titanic_train<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"female"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>female_pct <span class="ot">&lt;-</span> (total_females<span class="sc">/</span>total_passengers)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Percentage of passengers who were female:"</span>, <span class="fu">round</span>(female_pct, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage of passengers who were female: 35.24 %</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Survival percentage </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>total_survivors <span class="ot">&lt;-</span> <span class="fu">sum</span>(titanic_train<span class="sc">$</span>Survived <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>survival_pct <span class="ot">&lt;-</span> (total_survivors<span class="sc">/</span>total_passengers)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Percentage of passengers who survived:"</span>, <span class="fu">round</span>(survival_pct, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage of passengers who survived: 38.38 %</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Percentage of female passengers who survived</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>total_survived_fem <span class="ot">&lt;-</span> <span class="fu">sum</span>(titanic_train<span class="sc">$</span>Survived <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> titanic_train<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"female"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>survived_fem_pct <span class="ot">&lt;-</span> (total_survived_fem<span class="sc">/</span>total_females)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Percentage of female passengers who survived:"</span>, <span class="fu">round</span>(survived_fem_pct, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage of female passengers who survived: 74.2 %</code></pre>
</div>
</div>
<p>The dataset contains 891 rows and 12 variables, including passenger demographics, ticket and cabin details, and survival status. Approximately 35.24% of passengers were female, and 38.38% survived. Among female passengers, the survival rate was notably higher at 74.2%, highlighting the strong influence of gender on survival outcomes. This aligns with historical accounts of the “women and children first” policy during evacuation.</p>
</section>
<section id="gender-and-survival" class="level2">
<h2 class="anchored" data-anchor-id="gender-and-survival">Gender and Survival</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">fill =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span>  </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Survival Rates by Gender"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Gender"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Survival Status"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart and calculated statistics reveal a significant difference in survival rates based on gender. A much higher percentage of female passengers survived compared to male passengers, as evident from the dominant blue segment in the female bar, representing survivors. In contrast, the male bar shows a larger red segment, indicating that the majority of male passengers did not survive. These findings align with the “women and children first” policy that prioritised women during the evacuation. The statistics further support this observation, with approximately 74% of female passengers surviving, compared to a much lower survival rate of around 19% for males. This disparity highlights the influence of social norms and emergency protocols on survival outcomes during the Titanic disaster.</p>
</section>
<section id="age-and-survival" class="level2">
<h2 class="anchored" data-anchor-id="age-and-survival">Age and Survival</h2>
<p>Age is another critical factor to consider, as we often wonder whether children and younger adults had higher survival rates. To explore this, we create a density plot of passenger ages to distinguish between survival statuses.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">fill =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">adjust =</span> <span class="fl">1.1</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Density Plot of Passenger Ages by Survival Status"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Survival Status"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For children under 10 years old, there is a local peak in the density of survivors, indicating a high proportion of children within this age group among survivors. This aligns with the “women and children first” policy implemented during the evacuation. In contrast, the density of non-survivors is lower for young passengers, suggesting that children were less represented among those who did not survive.</p>
<p>For teenagers and young adults, specifically those between 15 and 30 years old, the densities of survivors and non-survivors overlap. The non-survivor density exhibits a global peak around this age group, particularly concentrated at approximately 24 years old. This indicates that individuals in their mid-twenties were highly represented among the non-survivors. While both groups include a significant proportion of passengers from this age range, the proportion of this age group is higher among non-survivors than among survivors. (It is important to note that density reflects the distribution within each group, not absolute numbers. This peak signifies a higher proportion of non-survivors in this age group relative to other ages within the non-survivor category. Additionally, the area under each curve always accumulates to 100%, representing the proportions within each group.)</p>
<p>For middle-aged and older adults, aged 30 and above, both densities gradually decrease, reflecting the lower number of passengers in this age range on board. The densities overlap and fluctuate slightly but remain relatively stable across this range. Notably, for passengers aged around 58 and older, the non-survivor density becomes more pronounced, suggesting that this group was more heavily represented among non-survivors. This pattern may reflect the physical challenges older individuals faced during the evacuation or the prioritisation of younger passengers and families. Overall, the density plot suggests that younger passengers, particularly children, were highly represented among survivors, while older passengers comprised a higher percentage of non-survivors.</p>
<p>Since gender may also play a significant role in passenger survival, we aim to explore whether age distributions differ between male and female passengers and between survivors and non-survivors. To visualise this, we create a ridge plot comparing the age distributions across these groups.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> <span class="fu">interaction</span>(Sex, <span class="fu">factor</span>(Survived)), <span class="at">fill =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">"female.0"</span> <span class="ot">=</span> <span class="st">"Female (Did Not Survive)"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">"female.1"</span> <span class="ot">=</span> <span class="st">"Female (Survived)"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>      <span class="st">"male.0"</span> <span class="ot">=</span> <span class="st">"Male (Did Not Survive)"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>      <span class="st">"male.1"</span> <span class="ot">=</span> <span class="st">"Male (Survived)"</span>)) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span> </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Ridge Plot of Age Distributions by Gender and Survival Status"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Gender &amp; Survival Status"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Survival Status"</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Picking joint bandwidth of 4.44</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The ridge plot reveals distinct differences in the age distributions of passengers based on gender and survival status. Among female survivors, there is a peak for younger passengers, particularly children under the age of 10. This pattern suggests that young females were prioritised during the evacuation, consistent with the “women and children first” policy. An even higher peak is observed for male survivors in this age group, indicating that young boys also benefited significantly from the prioritisation of children during the evacuation process. However, when examining children who did not survive, a relatively higher proportion is seen among female non-survivors compared to male non-survivors, suggesting that children represented a substantial proportion of female non-survivors.</p>
<p>Across all four distributions, the most represented age group (the peaks) is around 25 years old, with the highest peak and concentration observed among male non-survivors. This sharp peak for young and middle-aged males highlights that they were overrepresented among non-survivors, likely reflecting the lower priority given to adult males during the evacuation. In contrast, female survivors show relatively higher densities in this age range (20–40 years). Female non-survivors also exhibit noticeable densities in this range, particularly among older adults, indicating that older women made up a considerable proportion of female non-survivors.</p>
<p>Older adults, particularly those aged 50 and above, exhibit similar densities among survivors for both genders, with a slight peak for male survivors around the age of 80, which is somewhat surprising. For non-survivors in this age group, male densities are noticeably higher, suggesting that older individuals faced significant challenges during evacuation. These challenges may have included physical limitations or reduced prioritisation compared to younger passengers and families.</p>
<p>Overall, the plot underscores the combined influence of gender and age on survival outcomes. Among females, there are significant proportions represented across almost all age groups for both survivor and non-survivor densities. Among males, there is a highly concentrated group of young adult non-survivors, while male children have a notably high proportion among survivors. These patterns reflect the societal norms and evacuation protocols during the Titanic disaster.</p>
</section>
<section id="family-presence-and-survival" class="level2">
<h2 class="anchored" data-anchor-id="family-presence-and-survival">Family Presence and Survival</h2>
<p>The survival rates of passengers may also be influenced by whether they had family members on board. This is because the presence of family members could have provided support, assistance, and coordination during the chaotic evacuation process. To investigate this, we create a binary variable, <code>Family</code>, indicating whether a passenger had at least one sibling or parent on the ship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>titanic_train<span class="sc">$</span>Family <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(titanic_train<span class="sc">$</span>SibSp <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">|</span> titanic_train<span class="sc">$</span>Parch <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Family, <span class="at">fill =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span>  </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span>  </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Survival Status Based on Family Presence"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Family Onboard"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count of Passengers"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Survival Status"</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart illustrates the survival status of passengers based on whether they had family members onboard the Titanic. Passengers without family onboard overwhelmingly constitute a significantly larger group of non-survivors. This suggests that traveling alone significantly reduced the likelihood of survival, possibly due to the lack of support during the chaotic evacuation process. At the same time, this group also represents the largest overall category, indicating that the majority of passengers traveled alone.</p>
<p>In contrast, passengers who had family onboard exhibited a more balanced distribution between survivors and non-survivors. This suggests that the presence of family members may have provided crucial assistance and coordination, improving the chances of survival. However, it also highlights that survival was not guaranteed, even with familial support, emphasizing the unpredictable and challenging circumstances during the disaster.</p>
</section>
<section id="family-presence-and-survival-1" class="level2">
<h2 class="anchored" data-anchor-id="family-presence-and-survival-1">Family Presence and Survival</h2>
<p>Ticket fare is often considered a proxy for wealth and social class, as higher fares were typically associated with first-class passengers who had better accommodations and greater access to lifeboats. Thus, we aim to determine whether paying more for a ticket correlates with higher survival odds.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Fare, <span class="at">y =</span> <span class="fu">factor</span>(Survived), <span class="at">fill =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Box Plot of Ticket Fare by Survival Status"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Ticket Fare"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Survival Status"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Survival Status"</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The box plot reveals a clear relationship between ticket fare and survival status among Titanic passengers. Both box plots are positively skewed, as indicated by the median being closer to the first quartile. The central value for ticket fares among survivors is moderately higher compared to non-survivors, and their fares (even the middle range) exhibit a wider range, extending to significantly higher prices. This includes several outliers who paid exceptionally high ticket prices. These findings suggest that passengers in first-class accommodations, typically associated with higher fares, had better access to lifeboats and, consequently, a greater likelihood of survival.</p>
<p>In contrast, non-survivors show a lower median fare and a narrower range of ticket prices, but with many outliers in the higher fare range. The middle 50% of non-survivors paid fares within the range of approximately 10 to 25, suggesting that the majority of passengers who did not survive were in lower ticket classes. This highlights that passengers paying less for their fares were less likely to survive, likely due to limited access to lifeboats and less advantageous accommodations.</p>
<p>A particularly striking observation is the presence of outliers among survivors with fares exceeding 500. These high-paying passengers likely benefited from their wealth and social status, securing priority during the evacuation process. The disparity in fare distributions between survivors and non-survivors underscores the class-based inequalities in survival chances on the Titanic.</p>
<p>Overall, the box plot highlights the significant role of wealth and social class in shaping survival outcomes. Passengers who survived the tragedy paid higher fares overall, reflecting the unequal distribution of lifeboat access and evacuation opportunities. Conversely, passengers who did not survive paid lower fares, likely opting for lower-class accommodations, and faced greater challenges, emphasizing the stark class divisions on board the Titanic.</p>
</section>
<section id="ticket-fare-and-class" class="level2">
<h2 class="anchored" data-anchor-id="ticket-fare-and-class">Ticket Fare and Class</h2>
<p>Age and ticket fare may be correlated, as different age groups might have had varying financial means and travel arrangements. Younger passengers were often traveling with families, which may have influenced their class and ticket prices. Conversely, older passengers, particularly those traveling alone, might have been more likely to afford higher fares and first-class accommodations. This section investigates the relationship between age and fare.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Fare)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#00BFC4"</span>) <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatter Plot of Age vs. Fare"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ticket Fare"</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot of age versus ticket fare reveals several patterns in the relationship between these two variables. Young children, as well as young and middle-aged passengers, particularly those aged below 40, are predominantly clustered in the lower fare range, with most fares below 50. This pattern suggests that younger passengers were more likely to travel in lower ticket classes, possibly due to traveling with families or in groups, which may have reduced individual ticket costs. However, there are also many individuals in this age group who paid significantly higher ticket prices.</p>
<p>In contrast, older passengers, especially those aged 40 and above, exhibit a more evenly distributed range of ticket fares. While many older individuals also paid lower fares, there are many others who paid significantly higher amounts. These high-fare outliers indicate that some older passengers had the financial means to afford first-class accommodations, which offered greater comfort and increased access to lifeboats.</p>
<p>The trend line on the plot shows a slight positive slope, indicating a weak positive correlation between age and fare. This suggests that older passengers were somewhat more likely to pay higher fares on average, though the relationship is not strong. Additionally, several high-fare outliers are scattered across various age groups, representing passengers who paid premium prices, likely for first-class accommodations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(titanic_train, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Fare, <span class="at">color =</span> <span class="fu">factor</span>(Survived), <span class="at">shape =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="fu">aes</span>(<span class="at">linetype =</span> <span class="fu">factor</span>(Survived))) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">17</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Did Not Survive"</span>, <span class="st">"Survived"</span>)) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scatter Plot of Age vs. Fare by Survival Status"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Ticket Fare"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Survival Status"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">shape =</span> <span class="st">"Survival Status"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"Survival Status"</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot of age versus fare, differentiated by survival status, reveals a few trends when considering age and fare together. Survivors, represented by teal triangles, show an overall broader spread across fare ranges, with a noticeable presence in higher fare ranges across most age groups. This suggests that paying higher fares, often associated with first-class accommodations, increased survival chances regardless of age.</p>
<p>Non-survivors, represented by red circles, show a more concentrated pattern in the lower fare range across nearly all age groups. This clustering indicates that passengers in lower ticket classes, regardless of their age, were more likely to face challenges during evacuation. The more limited dispersion of non-survivors into higher fare ranges highlights the critical role of ticket class in influencing survival outcomes.</p>
<p>The trend lines further reinforce this relationship. The teal trend line for survivors indicates a slight positive correlation between age and fare, showing that older survivors tended to pay higher fares. In contrast, the red trend line for non-survivors is relatively flat, suggesting a weaker relationship between age and fare for those who did not survive.</p>
<p>In summary, passengers who survived were more likely to have paid higher fares across age groups, reflecting the advantages conferred by wealth and higher social class. Non-survivors, on the other hand, were predominantly concentrated in the lower fare ranges regardless of age, underscoring the disadvantage faced by lower-class passengers in terms of survival.</p>
</section>
</section>
<section id="how-did-family-size-gender-age-and-socio-economic-class-influence-survival-outcomes-on-the-titanic" class="level1">
<h1>How did family size, gender, age, and socio-economic class influence survival outcomes on the Titanic?</h1>
<p>In this section, we analyse whether family size impacts the survival rate of a passenger, specifically exploring whether having a larger family improved survival chances on the Titanic. To investigate this, we created a new variable, <code>FamilySize</code>, by summing <code>SibSp</code> (siblings/spouses) and <code>Parch</code> (parents/children). This represents the total family members each passenger had onboard. Summary statistics for <code>FamilySize</code> reveal a skewed distribution, with most passengers having no or very few family members onboard.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.9046  1.0000 10.0000 </code></pre>
</div>
</div>
<p>Next, we created a new variable, <code>FamilyCategory</code>, to classify passengers by family size: “Alone” (family size 0), “Small” (1–2), and “Large” (&gt;2). The majority of passengers (537) traveled alone, 263 belonged to small families, and only 91 were part of large families. This highlights that traveling alone was the most common family configuration on the Titanic, with few passengers in larger family groups.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart above analyzes survival rates based on family configuration, highlighting how family size influenced survival outcomes.</p>
<p>Passengers traveling alone had the lowest survival rate, with approximately 30% surviving. This suggests a significant disadvantage for individuals without family support during the chaotic evacuation. In contrast, passengers in small families had a notably higher survival rate, about 26% greater than those traveling alone, likely benefiting from the support and coordination of a small group. Large families experienced a lower survival rate compared to small families, with a difference of about 22%, though their survival rate was slightly higher than those traveling alone. This may reflect the challenges large families faced in staying together and securing lifeboat access for everyone.</p>
<p>Overall, passengers in small families had the best survival chances. While traveling alone posed the greatest challenges, survival rates for those in large families were only slightly better, suggesting that larger family sizes offered diminishing returns in survival advantages.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Building on the previous analysis of family configuration and its impact on survival outcomes, we now examine how gender and passenger class influenced survival rates. The grouped bar chart highlights the interplay between these factors, providing deeper insights into survival patterns on the Titanic.</p>
<p>Among first-class passengers, females had a notably high survival rate compared to males, with the majority of women surviving, as shown by the prominent teal bars. In contrast, most first-class men did not survive. This trend reflects the prioritisation of women during evacuation. In second class, female passengers again show higher survival rates than males, though overall survival rates are lower than in first class. Most second-class men did not survive, underscoring the consistent lower prioritisation of men. In third class, stark disparities emerge: while half the women survived, the survival rate for men decreases significantly, reflecting structural disadvantages like limited lifeboat access and poorer evacuation conditions.</p>
<p>Overall, women consistently had better chances of survival than men, and first-class passengers fared significantly better than those in third class.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DWV_Assignment-1_VAN_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Expanding on the earlier analyses, this visualization examines the distribution of age among survivors and non-survivors, segmented by passenger class.</p>
<p>In first class, the survival curve peaks around the 20–40 age range, indicating a higher concentration of this demographic among survivors. Non-survivors exhibit a more even distribution with a slight skew toward older passengers, suggesting a higher proportion of older individuals among those who did not survive. Second-class passengers show a different pattern, with survivors concentrated in the 20–40 age range and a secondary peak among children under 10. Non-survivors similarly peak in the 20–40 range, with higher density as well as among older passengers above 50. In third class, similar patterns emerge as in the second class.</p>
<p>Overall, first-class age distributions are more balanced between survivors and non-survivors, while second and third classes show sharper disparities. However, the second and third classes highlight the importance of prioritizing children, as they are predominantly represented among survivors.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>To summarize, the analysis reveals that survival on the Titanic was influenced by family size, gender, age, and socio-economic class. Passengers in small families had the highest survival rates, benefiting from mutual support, while those traveling alone faced the greatest disadvantages. Women consistently had better survival outcomes than men across all classes, reflecting prioritisation during evacuation, and first-class passengers fared significantly better than those in second or third class. Age also played a role, with children under 10 being consistently prioritised across all classes. These findings highlight how a combination of familial support, demographic factors, and socio-economic status shaped survival outcomes during the Titanic disaster.</p>
</section>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>